name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.5'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
      
      - name: Quick security check
        run: |
          # Ensure no sensitive files are tracked
          if git ls-files | grep -E '\.(env|tokens\.json|key|pem)$' | grep -v '.example'; then
            echo "::error::Sensitive files found in repository!"
            exit 1
          fi
